theme = "tokyonight"

[editor]
true-color = true       # for servers
bufferline = "multiple"


[editor.soft-wrap]
enable = true
max-wrap = 25
wrap-indicator = ""
wrap-at-text-width = false

[editor.lsp]
display-inlay-hints = true

[keys.insert]
C-p = "normal_mode"

[keys.normal]
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_down"
C-v = "vsplit"
C-f = "file_picker"
C-p = "file_picker_in_current_directory"
"$" = ["goto_line_end"]
"^" = ["goto_line_start"]
"=" = [":format"]
